// constants.js
export const piecesInitialState = [
  [
    { type: "♖", color: "black" },
    { type: "♘", color: "black" },
    { type: "♗", color: "black" },
    { type: "♕", color: "black" },
    { type: "♔", color: "black" },
    { type: "♗", color: "black" },
    { type: "♘", color: "black" },
    { type: "♖", color: "black" },
  ],
  Array(8).fill(null),
  Array(8).fill(null),
  Array(8).fill(null),
  Array(8).fill(null),
  Array(8).fill(null),
  [
    { type: "♙", color: "black" },
    { type: "♙", color: "black" },
    { type: "♙", color: "black" },
    { type: "♙", color: "black" },
    { type: "♙", color: "black" },
    { type: "♙", color: "black" },
    { type: "♙", color: "black" },
    { type: "♙", color: "black" },
  ],
  Array(8).fill(null),
  [
    { type: "♙", color: "white" },
    { type: "♙", color: "white" },
    { type: "♙", color: "white" },
    { type: "♙", color: "white" },
    { type: "♙", color: "white" },
    { type: "♙", color: "white" },
    { type: "♙", color: "white" },
    { type: "♙", color: "white" },
  ],
  Array(8).fill(null),
  Array(8).fill(null),
  Array(8).fill(null),
  Array(8).fill(null),
  [
    { type: "♖", color: "white" },
    { type: "♘", color: "white" },
    { type: "♗", color: "white" },
    { type: "♕", color: "white" },
    { type: "♔", color: "white" },
    { type: "♗", color: "white" },
    { type: "♘", color: "white" },
    { type: "♖", color: "white" },
  ],
];
